{% set name = "TorchEEG" %}
{% set version = "1.0.9" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: .

build:
  number: 0
  noarch: python
  script: "python -m pip install . --no-deps --ignore-installed -vv"

requirements:
  build:
    - python
  run:
    - python
    - tqdm>=4.64.0
    - numpy>=1.21.5
    - pandas>=1.3.5
    - scipy>=1.7.3
    - scikit-learn>=1.0.2
    - python-lmdb>=1.3.0
    - einops>=0.4.1
    - mne-base>=1.0.3
    - xmltodict>=0.13.0
    - networkx>=2.6.3
    - PyWavelets>=1.3.0
    - spectrum>=0.8.1

about:
  home: https://github.com/tczhangzhi/torcheeg
  license: MIT
  summary: 'TorchEEG is a library built on PyTorch for EEG signal analysis.'
  description: |
    TorchEEG is a library built on PyTorch for EEG signal analysis. TorchEEG aims to provide a plug-and-play EEG analysis tool, so that researchers can quickly reproduce EEG analysis work and start new EEG analysis research without paying attention to technical details unrelated to the research focus.
